Sync with 3eg-next

diff --git a/project-spec/meta-user/recipes-apps/zuca-test-suite/files/usb-bist b/project-spec/meta-user/recipes-apps/zuca-test-suite/files/usb-bist
--- a/project-spec/meta-user/recipes-apps/zuca-test-suite/files/usb-bist
+++ b/project-spec/meta-user/recipes-apps/zuca-test-suite/files/usb-bist
@@ -6,7 +6,7 @@
 # For more information regarding USB Classes: https://en.wikipedia.ort/wiki/USB
 
 # How to call this script?
-# Call this script with only one parameter: usb-bist <port_number>
+# Call this script with only one parameter: usb_bist <port_number>
 # <port_number> between 1 and 5
 # 1 - port 1(up) of USB 2.0 stacked connector
 # 2 - port 2(down) of USB 2.0 stacked connector
@@ -20,13 +20,19 @@
 # 2. Verify that the devices have the correct bInterfaceClass
 # 3. Verify that the port to which the devices are connected have the corrent speed
 
-# Return value: 0 for success; 1 for failure
+# Return value:
+# 0 - Success
+# 1 - No device connected
+# 2 - Wrong device class
+# 3 - Wrong device speed
+# 4 - Wrong type-c orientation
+# 5 - Wrong arguments
 
 # Reset all USB devices. We perform this operation because is some circumstances
 # a USB 3.0 device may be connected to USB 2.0 bus. In such a case the test will
 # fail. By resetting all USB devices we force the system to re-enumerate all
 # devices.
-usb-reset
+usb_reset
 
 # We need a delay here to establish a correct connection with all USB devices.
 sleep 2
@@ -61,7 +67,7 @@ USB_BUS_2_PORT_1_INTERFACE="2-1:1.0"
 
 if [ $# -ne "$ARGS" ]; then
 	echo "Wrong number of arguments!"
-	exit 4
+	exit 5
 fi
 
 case "$1" in
@@ -192,7 +198,7 @@ case "$1" in
 		;;
 	*)
 		echo "Wrong option!"
-		exit 4
+		exit 5
 esac
 
 exit 0
